#!/bin/bash
set -e
n=${1%.*}
echo "Compiling profile: $n"
ghc --make $n.hs -prof -fforce-recomp -rtsopts
echo "Running profile..."
time ./$n +RTS -pa
echo "...done."
echo "Removing temp files..."
rm ./$n
rm ./*.hi
rm ./*.o
echo "...done."
echo "Output in: ./$n.prof"
