#!/bin/bash
set -e
n=${1%.*}
ts=${2%.*}
echo "Compiling profile: $n $ts"
ghc --make $n.hs -prof -fforce-recomp
echo "Running profile..."
time ./$n $ts +RTS -P -V0.001
echo "...done."
echo "Removing temp files..."
rm ./$n
rm ./*.hi
rm ./*.o
echo "...done."
mv ./$n.prof ./$n-$ts.prof
echo "Output in: ./$n-$ts.prof"
